version: "3.7"
services:
  debezium:
    image: debezium/connect:1.4
    environment:
      BOOTSTRAP_SERVERS: 192.168.1.68:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://192.168.1.68:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://192.168.1.68:8081
    depends_on: []
    ports: 
      - "8083:8083"

  schema-registry:
    image: confluentinc/cp-schema-registry:5.5.3
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 192.168.1.68:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    ports:
      - "8081:8081"
